# Generated by Django 6.0.3 on 2026-04-05 08:18

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('students', '0001_initial'),
        ('teachers', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Group',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Название группы')),
                ('course_type', models.CharField(choices=[('KIDS_ENGLISH', 'Kids English'), ('GENERAL_ENGLISH', 'General English'), ('IELTS', 'IELTS'), ('MATH', 'Математика'), ('SAT', 'SAT')], default='GENERAL_ENGLISH', max_length=20, verbose_name='Тип курса')),
                ('level', models.CharField(blank=True, help_text='Для General English: Beginner, Elementary, Pre-Intermediate, Intermediate, Upper-Intermediate, Advanced', max_length=100, verbose_name='Уровень')),
                ('schedule_type', models.CharField(choices=[('EVEN', 'Чётные дни'), ('ODD', 'Нечётные дни')], default='EVEN', max_length=4, verbose_name='Расписание')),
                ('room', models.CharField(blank=True, max_length=50, verbose_name='Кабинет')),
                ('monthly_fee', models.DecimalField(decimal_places=0, default=400000, max_digits=12, verbose_name='Ежемесячная оплата (сум)')),
                ('max_students', models.PositiveIntegerField(default=12, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(30)], verbose_name='Макс. учеников')),
                ('duration_months', models.PositiveIntegerField(default=3, help_text='General English — 3 мес., IELTS скилл — 1 мес.', verbose_name='Длительность уровня (мес.)')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активная')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('teacher', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='groups', to='teachers.teacher', verbose_name='Учитель')),
            ],
            options={
                'verbose_name': 'Группа',
                'verbose_name_plural': 'Группы',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Enrollment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('enrolled_date', models.DateField(auto_now_add=True, verbose_name='Дата зачисления')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активен')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='enrollments', to='students.student', verbose_name='Ученик')),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='enrollments', to='groups.group', verbose_name='Группа')),
            ],
            options={
                'verbose_name': 'Зачисление',
                'verbose_name_plural': 'Зачисления',
                'ordering': ['-enrolled_date'],
                'unique_together': {('student', 'group')},
            },
        ),
    ]
