# Generated by Django 6.0.3 on 2026-04-05 08:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('groups', '0001_initial'),
        ('teachers', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='group',
            name='time_slot',
            field=models.CharField(blank=True, max_length=50, verbose_name='Время'),
        ),
        migrations.CreateModel(
            name='SundayEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Название')),
                ('date', models.DateField(verbose_name='Дата')),
                ('time_slot', models.CharField(max_length=50, verbose_name='Время')),
                ('room', models.CharField(max_length=50, verbose_name='Кабинет')),
                ('description', models.TextField(blank=True, verbose_name='Описание')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('teacher', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='teachers.teacher', verbose_name='Учитель')),
            ],
            options={
                'verbose_name': 'Воскресный ивент',
                'verbose_name_plural': 'Воскресные ивенты',
                'ordering': ['date', 'time_slot'],
            },
        ),
    ]
