# Generated by Django 6.0.3 on 2026-04-06 05:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('groups', '0002_group_time_slot_sundayevent'),
    ]

    operations = [
        migrations.AddField(
            model_name='group',
            name='color',
            field=models.CharField(choices=[('bg-t-1', 'Изумрудный (Зеленый)'), ('bg-t-2', 'Индиго (Сине-фиолетовый)'), ('bg-t-3', 'Янтарный (Оранжевый)'), ('bg-t-4', 'Океан (Синий)'), ('bg-t-5', 'Роза (Красный)'), ('bg-t-6', 'Серый (Нейтральный)')], default='bg-t-1', max_length=20, verbose_name='Цвет карточки'),
        ),
    ]
