# Generated by Django 6.0.4 on 2026-04-10 07:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0002_attendance_comment'),
    ]

    operations = [
        migrations.AddField(
            model_name='attendance',
            name='grade',
            field=models.CharField(blank=True, max_length=5, null=True, verbose_name='Оценка'),
        ),
    ]
